server:
  port: 4004

    ## REST CLIENT --> http://localhost:4004/api/patients
    ## API GATEWAY --> http://patient-service:8080/patients
  ## PATIENT SERVICE(SPRING BOOT APP) --> /patients  ---> Patients Array



  ## REST CLIENT --> http://localhost:4004/api-docs/patients
  ## API GATEWAY --> http://patient-service:8080/v3/api-docs



spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: patient-service-route
              uri: http://patient-service:8080
              predicates:
                - Path=/api/patients/**
              filters:
                - StripPrefix=1

            - id: api-docs-patient-route
              uri: http://patient-service:8080
              predicates:
                - Path=/api-docs/patients
              filters:
                - RewritePath=/api-docs/patients,/v3/api-docs


#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: patient-service-route
#          uri: http://patient-service:8080
#          predicates:
#            - Path=/api/patients/**
#          filters:
#            - StripPrefix=1
#
#        - id: api-docs-patient-route
#          uri: http://patient-service:8080
#          predicates:
#            - Path=/api-docs/patients
#          filters:
#            - RewritePath=/api-docs/patients,/v3/api-docs


